worker_processes 1;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server {
        listen 4430 ssl;

        ssl_protocols       TLSv1.3;
        ssl_certificate     /certs/server.crt;
        ssl_certificate_key /certs/server.key;

        location / {
            default_type application/json;
            return 200 '{\"mode\":\"classical\",\"algo\":\"RSA-2048 + ECDH-P256\",\"status\":\"ok\"}';
        }
    }
}
