worker_processes 1;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server {
        listen 4432 ssl;

        ssl_protocols TLSv1.3;

        ssl_certificate /certs/server.crt;
        ssl_certificate_key /certs/server.key;

        ssl_ecdh_curve mlkem768;

        location / {
            default_type application/json;
            return 200 '{"mode":"hybrid","algo":"P-384 + ML-DSA-65 + ML-KEM-768","status":"ok"}';
        }
    }
}